import optparse
##filter the SNPs identified by bcftools based on DP4/DP

def filter_dp4(infile,ratio):
	list = []#use a list to store passed-filter lines
	
	inFile = open(infile,'r')
	lines = inFile.readlines()
	inFile.close()
	
	for i in lines:
		if i.startswith("#"):
			list.append(i)#skip comment lines
		else:
			col = i.strip().split("\t")
			gt = col[-1]
			info = col[7]
			dp = info.split("DP=")[-1].split(";")[0]#extract DP value
			dp4 = info.split("DP4=")[-1].split(";")[0].split(",")#extract DP4 values
			if gt.startswith("0/0"):
				if (int(dp4[2])+int(dp4[3])) == 0:
					list.append(i) #add to list if there is no alt allele at this position
				else:
					continue
			elif gt.startswith("1/1") or gt.startswith("0/1"):
				if ((int(dp4[0])+int(dp4[1])) == 0) and ((float(dp4[2])+float(dp4[3]))/int(dp)>=ratio): 	
					list.append(i)#add to list if the snp passes ratio filter
				else:
					continue
			else:
				continue#skip if GT is 1/2 (two alt alleles) or ./. (no data)
	return list
	
def main(infile,ratio,outfile):
	outList = filter_dp4(infile,ratio)
	outFile = open(outfile,'w')
	
	for i in outList:
		outFile.write(i)
	outFile.close()
	
		
if __name__== '__main__':
	'''
	filter the vcf generated by bcftools based on dp4 value
	'''
    	# parser object for managing input options
	parser = optparse.OptionParser()

    	# essential data
	parser.add_option( '-i' , dest = 'infile' ,
                default = '' ,
                help = 'the input .bcftools.vcf file')
	parser.add_option( '-r' , dest = 'ratio' ,  type="float",
               	default = '1.0' ,
	        help = 'specify the cutoff for the ratio of DP4/DP, default = 1.0' )
	parser.add_option( '-o' , dest = 'outfile' ,
                default = '' ,
                help = 'specify output filename, i.e. .bcftools.dp4_1.vcf' )

    	# load the inputs
	(options , args) = parser.parse_args()
    
    	# process the inputs
    	# note: all commandline inputs are str by default
	infile = options.infile
	ratio = options.ratio
	outfile = options.outfile
	main(infile,ratio,outfile)
